# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1.4
# Builder stage
FROM node:lts-alpine AS builder
WORKDIR /app
# Copy manifest and TS config
COPY package.json package-lock.json tsconfig.json ./
# Copy source code
COPY src ./src
# Install deps and build
RUN npm install --ignore-scripts && npm run build

# Runner stage
FROM node:lts-alpine AS runner
WORKDIR /app
# Copy production deps
COPY package.json package-lock.json ./
RUN npm install --production --ignore-scripts
# Copy built assets
COPY --from=builder /app/build ./build

# Default command: node build/index.js
ENTRYPOINT ["node", "build/index.js"]
